#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

SYSTEMDDIR="/root/writable/system-data/etc/systemd"
JOBDIR="${SYSTEMDDIR}/system"

[ -e "/root/writable/system-data/etc/modules-load.d/libcomposite.conf" ]  || \
	echo "libcomposite" >/root/writable/system-data/etc/modules-load.d/libcomposite.conf

[ -d "/root/writable/system-data/var/lib/misc" ]  || \
	mkdir -p /root/writable/system-data/var/lib/misc

[ -e "/root/writable/system-data/var/lib/misc/enable-musb.sh" ]  || \
	cp /enable-musb.sh /root/writable/system-data/var/lib/misc/enable-musb.sh

SERVICENAME="musb-enable.service"

if [ ! -L "${JOBDIR}/multi-user.target.wants/${SERVICENAME}" ]; then
       cp /${SERVICENAME} ${JOBDIR}/${SERVICENAME}
	   [ -d "${JOBDIR}/multi-user.target.wants" ]  || \
		   mkdir -p ${JOBDIR}/multi-user.target.wants
	   ln -s /etc/systemd/system/${SERVICENAME} ${JOBDIR}/multi-user.target.wants/${SERVICENAME}
fi

SERVICENAME="serial-getty@ttyGS0.service"

if [ ! -L "${JOBDIR}/getty.target.wants/${SERVICENAME}" ]; then
       cp /root/lib/systemd/system/serial-getty@.service ${JOBDIR}/${SERVICENAME}
       ln -s /etc/systemd/system/${SERVICENAME} ${JOBDIR}/getty.target.wants/${SERVICENAME}
fi
